### ISSUE TITLE
Prefix action types

### ISSUE THREAD

**Issue by fabienjuif** [Trampss/trampss-redux-data-store#17]
From @bpetetot

To avoid having too generic actions names, you might should prefix the actions names like (and keep the upper case convention) : @trampss/SET_TODOS

**Comment by bpetetot** [comment]
You may need to add also the path, to avoid conflicts like that : 
`factory('id')('search')('users')`  =>  action `SET_users`
`factory('id')('followers')('users')`  =>  action `SET_users`

**Comment by fabienjuif** [comment]
Yeah I though about it when I wrote the first version but I don't like the idea that actions are dependent to the reducer store path.

With a lib like `redux-saga` if I wanna "catch" an action, I should give the path.
And if I move the reducer for whatever reason, all my catched actions will be KO.

**Comment by fabienjuif** [comment]
#26
